# Generated by Django 5.0.4 on 2024-04-15 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('tagline', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('actors', models.CharField(blank=True, max_length=500)),
                ('stage_director', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(default=2020)),
                ('ganre', models.CharField(max_length=100)),
                ('primera', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='movie.category')),
            ],
        ),
    ]
